Update java-test.yml

diff --git a/.github/workflows/java-test.yml b/.github/workflows/java-test.yml
--- a/.github/workflows/java-test.yml
+++ b/.github/workflows/java-test.yml
@@ -56,29 +56,25 @@ jobs:
         Start-Process -FilePath chrome_installer.exe -Args "/silent /install" -NoNewWindow -Wait
       shell: powershell
 
+    - name: Print runner IP address
+      run: |
+        echo "Runner IP address:"
+        ipconfig
+      shell: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.EXE -command ". '{0}'"
+
+    - name: Check database connectivity
+      run: |
+        echo "Checking database connectivity..."
+        mysql -h nmm-ue1-test-rds-pp1-mysql.cyfcbagzyvft.us-east-1.rds.amazonaws.com -P 3306 -u ppuser -puTBHF35D9QqvLMh1X1FBX93nGgnqpgBc -e "select 1" || echo "Failed to connect to database"
+      shell: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.EXE -command ". '{0}'"
+      env:
+        JAVA_HOME: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\21.0.4-7.0\x64
+
     - name: Create necessary directories
       run: |
         New-Item -Path target -ItemType Directory -Force
         New-Item -Path target/allure-results -ItemType Directory -Force
         New-Item -Path target/allure-report -ItemType Directory -Force
-      shell: powershell
-
-    - name: Install MySQL client
-      run: |
-        if (Test-Path -Path "C:\ProgramData\chocolatey\bin\choco.exe") {
-          choco install mysql
-        } else {
-          Write-Output "Chocolatey not found, installing MySQL client manually..."
-          Invoke-WebRequest -Uri https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.28-winx64.zip -OutFile mysql.zip
-          Expand-Archive -Path mysql.zip -DestinationPath $Env:ProgramFiles
-          $Env:Path += ";$Env:ProgramFiles\mysql-8.0.28-winx64\bin"
-        }
-      shell: powershell
-
-    - name: Check database connectivity
-      run: |
-        echo "Checking database connectivity..."
-        mysql -h nmm-ue1-test-rds-pp1-mysql.cyfcbagzyvft.us-east-1.rds.amazonaws.com -P 3306 -u ppuser -puTBHF35D9QqvLMh1X1FBX93nGgnqpgBc -e "select 1"
       shell: powershell
 
     - name: Run tests with Maven
@@ -99,9 +95,6 @@ jobs:
         RUN_CHECK_INFO_REPORTS: ${{ github.event.inputs.run_check_info_reports }}
         RUN_CHECK_SCRAPER_INFO: ${{ github.event.inputs.run_check_scraper_info }}
         RUN_CHECK_FEE_TAG_COMISSION: ${{ github.event.inputs.run_check_fee_tag_comission }}
-        DB_URL: jdbc:mysql://nmm-ue1-test-rds-pp1-mysql.cyfcbagzyvft.us-east-1.rds.amazonaws.com:3306/db
-        DB_USER: ppuser
-        DB_PASSWORD: uTBHF35D9QqvLMh1X1FBX93nGgnqpgBc
 
     - name: Generate Allure Report
       run: |
